Resolver fixes, other

diff --git a/debian/postrm b/debian/postrm
--- a/debian/postrm
+++ b/debian/postrm
@@ -3,44 +3,38 @@
 NAME=jmpapi
 
 case "$1" in
-    remove)
-        if [ -x insserv ]; then
-            # Stop the service
-            service $NAME stop || true
+  remove)
+    # Stop the service
+    service $NAME stop || true
 
-            # Uninstall init.d script
-            insserv -r $NAME
-        else
-            # Stop the service
-            invoke-rc.d $NAME stop || true
+    # Uninstall service
+    if [ -e /etc/systemd/system/$NAME.service ]; then
+      rm -f /etc/systemd/system/$NAME.service
+      systemctl daemon-reload
+    fi
+    ;;
 
-            # Uninstall init.d script
-            update-rc.d -f $NAME remove
-        fi
-        ;;
+  purge)
+    rm -rf /etc/$NAME /etc/default/$NAME /var/lib/$NAME /var/log/$NAME
 
-    purge)
-        # Remove files
-        rm -rf /etc/$NAME /etc/default/$NAME /var/lib/$NAME /var/log/$NAME
+    # Remove user if it exists
+    if getent passwd $NAME >/dev/null; then
+      echo -n "Removing system user $NAME..."
+      if userdel $NAME 2>/dev/null; then
+        echo "done"
+      else
+        echo "failed"
+      fi
+    fi
 
-        # Remove user if it exists
-        if getent passwd $NAME >/dev/null; then
-            echo -n "Removing system user $NAME..."
-            if userdel $NAME 2>/dev/null; then
-                echo "done"
-            else
-                echo "failed"
-            fi
-        fi
-
-        # Remove group if it exists
-        if getent group $NAME >/dev/null; then
-            echo -n "Removing system group $NAME..."
-            if groupdel $NAME 2>/dev/null; then
-                echo "done"
-            else
-                echo "failed"
-            fi
-        fi
-        ;;
+    # Remove group if it exists
+    if getent group $NAME >/dev/null; then
+      echo -n "Removing system group $NAME..."
+      if groupdel $NAME 2>/dev/null; then
+        echo "done"
+      else
+        echo "failed"
+      fi
+    fi
+    ;;
 esac
diff --git a/debian/preinst b/debian/preinst
--- a/debian/preinst
+++ b/debian/preinst
@@ -6,39 +6,35 @@ RUN=/var/run/$NAME
 LOG=/var/log/$NAME
 
 case "$1" in
-    install|upgrade)
-        if [ "$1" == "upgrade" ]; then
-            # Stop the service
-            if [ -x insserv ]; then
-                service $NAME stop || true
-            else
-                invoke-rc.d $NAME stop || true
-            fi
-        fi
+  install|upgrade)
+    if [ "$1" == "upgrade" ]; then
+      service $NAME stop || true
+    fi
 
-        # Create directories
-        test -d $ETC || mkdir -m 755 $ETC
-        test -d $RUN || mkdir -m 755 $RUN
-        test -d $LOG || mkdir -m 755 $LOG
+    # Remove old init.d script
+    if [ -e /etc/init.d/$NAME ]; then
+      update-rc.d -f $NAME remove 2>/dev/null
+      rm -f /etc/init.d/$NAME
+    fi
 
-        # Create group if it does not exist
-        if ! getent group $NAME >/dev/null; then
-            echo -n "Adding system group $NAME..."
-            if groupadd -r $NAME 2>/dev/null; then
-                echo "done"
-            else
-                echo "failed"
-            fi
-        fi
+    # Create group if it does not exist
+    if ! getent group $NAME >/dev/null; then
+      echo -n "Adding system group $NAME..."
+      if groupadd -r $NAME 2>/dev/null; then
+        echo "done"
+      else
+        echo "failed"
+      fi
+    fi
 
-        # Create user if it does not exist
-        if ! getent passwd $NAME >/dev/null; then
-            echo -n "Adding system user $NAME..."
-            if useradd -r -g $NAME $NAME 2>/dev/null; then
-                echo "done"
-            else
-                echo "failed"
-            fi
-        fi
-        ;;
+    # Create user if it does not exist
+    if ! getent passwd $NAME >/dev/null; then
+      echo -n "Adding system user $NAME..."
+      if useradd -r -g $NAME $NAME 2>/dev/null; then
+        echo "done"
+      else
+        echo "failed"
+      fi
+    fi
+    ;;
 esac
